#!/usr/bin/env bash
set -e

BASE_PATH="$PWD/"

no_finalize_for_tests=
while [[ "$#" -ne 0 ]]; do
  case "$1" in
  --base-path)
    shift
    # the relative path root to use for reporting filenames
    # this is mainly intended for suite mode, where this will be the suite root folder
    BASE_PATH="$1"
    # use the containing directory when --base-path is a file
    if [[ ! -d "$BASE_PATH" ]]; then
      BASE_PATH="$(dirname "$BASE_PATH")"
    fi
    # get the absolute path
    BASE_PATH="$(cd "$BASE_PATH"; pwd)"
    # ensure the path ends with / to strip that later on
    if [[ "${BASE_PATH}" != *"/" ]]; then
      BASE_PATH="$BASE_PATH/"
    fi
  ;;
  -T)
    BATS_ENABLE_TIMING="-T"
    ;;
  --no-finalize-for-tests)
    # this is used to reproduce the visible output halfway through a test run, when the finalizers have not yet run
    no_finalize_for_tests=1
    ;;
  esac
  shift
done

additional_lines=0

update_count_column_width() {
  count_column_width=$((${#count} * 2 + 2))
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    # additional space for ' in %s sec'
    count_column_width=$((count_column_width + ${#SECONDS} + 8))
  fi
  # also update dependent value
  update_count_column_left
}

update_screen_width() {
  screen_width="$(tput cols)"
  # also update dependent value
  update_count_column_left
}

update_count_column_left() {
  count_column_left=$((screen_width - count_column_width))
}

trap update_screen_width WINCH
update_screen_width

begin_suite() {
  retreat_additional_lines
  go_to_column 0
  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) "   \x1B[33;22msource\x1B[0ming \`%s'" "$1"
  clear_to_end_of_line
  go_to_column $count_column_left
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    buffer "%${#count}s/${count} in %s sec" "$index" "$SECONDS"
  else
    buffer "%${#count}s/${count}" "$index"
  fi
  go_to_column 1
}

begin_setup_file() {
  retreat_additional_lines
  go_to_column 0
  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) "   running \x1B[33;22msetup_file\x1B[0m in \`%s'" "$1"
  clear_to_end_of_line
  go_to_column $count_column_left
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    buffer "%${#count}s/${count} in %s sec" "$index" "$SECONDS"
  else
    buffer "%${#count}s/${count}" "$index"
  fi
  go_to_column 1
}

begin_teardown_file() {
  retreat_additional_lines
  go_to_column 0
  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) "   running \x1B[33;22mteardown_file\x1B[0m in \`%s'" "$1"
  clear_to_end_of_line
  go_to_column 1
}

begin() {
  retreat_additional_lines
  go_to_column 0
  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) '  \x1B[33;22msource\x1B[0ming `%s'\'' for test `%s'\''' "$(remove_prefix "$BASE_PATH" "$test_file")" "$name"
  clear_to_end_of_line
  go_to_column $count_column_left
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    buffer "%${#count}s/${count} in %s sec" "$index" "$SECONDS"
  else
    buffer "%${#count}s/${count}" "$index"
  fi
  go_to_column 1
}

begin_setup() {
  retreat_additional_lines
  go_to_column 0
  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) '   running \x1B[33;22msetup\x1B[0m for `%s'\''' "$name"
  clear_to_end_of_line
  go_to_column $count_column_left
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    buffer "%${#count}s/${count} in %s sec" "$index" "$SECONDS"
  else
    buffer "%${#count}s/${count}" "$index"
  fi
  go_to_column 1
}

begin_test() {
  retreat_additional_lines
  go_to_column 0
  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) '   %s' "$name"
  clear_to_end_of_line
  go_to_column $count_column_left
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    buffer "%${#count}s/${count} in %s sec" "$index" "$SECONDS"
  else
    buffer "%${#count}s/${count}" "$index"
  fi
  go_to_column 1  
}

begin_teardown() {
  retreat_additional_lines
  go_to_column 0
  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) '   running \x1B[33;22mteardown\x1B[0m for `%s'\''' "$name"
  clear_to_end_of_line
  go_to_column $count_column_left
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    buffer "%${#count}s/${count} in %s sec" "$index" "$SECONDS"
  else
    buffer "%${#count}s/${count}" "$index"
  fi
  go_to_column 1
}

# shellcheck source=lib/bats-core/common.bash
source "$BATS_ROOT/lib/bats-core/common.bash"

test_progress() { # <line number> <file> <code>
  line_number="$1"
  test_file="$2"
  
  code= # declare to appease shellcheck
  if ! bats_extract_line "$test_file" "$line_number" code; then
    # don't output lines that are not found in the file
    # this can happen for preprocessed files that are mapped to their source but contain more lines
    return
  fi

  buffer '\n'
  (( ++additional_lines ))
  go_to_column 0
  update_count_column_width
  bats_strip_string "$code" code
  buffer_with_truncation $((count_column_left - 1)) "     %s:%d: \`\x1B[33;22m%s\x1B[0m\`" "$(remove_prefix "$BASE_PATH" "$test_file")" "$line_number" "${code/$'\x1B'/}"
  clear_to_end_of_line
}

test_output() { # <output line>
  buffer '\n'
  (( ++additional_lines ))
  go_to_column 0

  update_count_column_width
  buffer_with_truncation $((count_column_left - 1)) '       > \x1B[34;22m%s\x1B[0m' "${1/$'\x1B'/}"
  clear_to_end_of_line
}

pass() {
  retreat_additional_lines
  go_to_column 0
  buffer ' ✓ %s' "$name"
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    set_color 2
    buffer ' [%sms]' "$1"
  fi
  advance
}

skip() {
  retreat_additional_lines
  local reason="$1"
  if [[ -n "$reason" ]]; then
    reason=": $reason"
  fi
  go_to_column 0
  buffer ' - %s (skipped%s)' "$name" "$reason"
  advance
}

fail() {
  retreat_additional_lines
  go_to_column 0
  set_color 1 bold
  buffer ' ✗ %s' "$name"
  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    set_color 2
    buffer ' [%s]' "$1"
  fi
  advance
}

log() {
  set_color 1
  buffer '   %s\n' "${1/$'\x1B'/}"
  clear_color
}

summary() {
  buffer '\n%d test' "$count"
  if [[ "$count" -ne 1 ]]; then
    buffer 's'
  fi

  buffer ', %d failure' "$failures"
  if [[ "$failures" -ne 1 ]]; then
    buffer 's'
  fi

  if [[ "$skipped" -gt 0 ]]; then
    buffer ', %d skipped' "$skipped"
  fi

  not_run=$((count - passed - failures - skipped))
  if [[ "$not_run" -gt 0 ]]; then
    buffer ', %d not run' "$not_run"
  fi

  if [[ -n "$BATS_ENABLE_TIMING" ]]; then
    buffer " in $SECONDS seconds"
  fi

  buffer '\n'
}

buffer_with_truncation() {
  local width="$1"
  shift
  local string

  # shellcheck disable=SC2059
  printf -v 'string' -- "$@"

  if [[ "${#string}" -gt "$width" ]]; then
    buffer '%s...' "${string:0:$((width - 4))}"
  else
    buffer '%s' "$string"
  fi
}

go_to_column() {
  local column="$1"
  buffer '\x1B[%dG' $((column + 1))
}

clear_to_end_of_line() {
  buffer '\x1B[K'
}

advance() {
  clear_to_end_of_line
  buffer '\n'
  clear_color
}

retreat_additional_lines() { # delete all additional lines
  if [[ "$additional_lines" -gt 0 ]]; then
    for _ in $(seq 1 "$additional_lines"); do
      go_to_column 0
      clear_to_end_of_line
      buffer '\x1B[1A'
      :
    done
    additional_lines=0
    go_to_column 1
  fi
}

set_color() {
  local color="$1"
  local weight=22

  if [[ "$2" == 'bold' ]]; then
    weight=1
  fi
  buffer '\x1B[%d;%dm' "$((30 + color))" "$weight"
}

clear_color() {
  buffer '\x1B[0m'
}

_buffer=

buffer() {
  local content
  # shellcheck disable=SC2059
  printf -v content -- "$@"
  _buffer+="$content"
}

flush() {
  printf '%s' "$_buffer"
  _buffer=
}

finish() {
  flush
  printf '\n'
}

[[ -n "$no_finalize_for_tests" ]] || trap finish EXIT

# shellcheck source=lib/bats-core/formatter.bash
source "$BATS_ROOT/lib/bats-core/formatter.bash"

bats_tap_stream_plan() {
  count="$1"
  index=0
  passed=0
  failures=0
  skipped=0
  name=
  update_count_column_width
}

bats_tap_stream_begin() {
  index="$1"
  name="$2"
  begin
  flush
}

bats_tap_stream_setup() {
  name="$2"
  begin_setup
  flush
}

bats_tap_stream_setup_finished() {
  begin_test
  flush
}

bats_tap_stream_teardown() {
  begin_teardown
  flush
}
  
bats_tap_stream_ok() {
  index="$1"
  ((++passed))
  if [[ "$1" == "--duration" ]]; then
    pass "$2"
  else
    pass
  fi
  flush
}

bats_tap_stream_skipped() {
  index="$1"
  ((++skipped))
  skip "$3"
}

bats_tap_stream_not_ok() {
  index="$1"
  ((++failures))
  if [[ "$1" == "--duration" ]]; then
    fail "$2"
  else
    fail
  fi
}

bats_tap_stream_comment() {
  log "$1"
}

bats_tap_stream_exit_test() {
  :
}

bats_tap_stream_begin_file() {
  begin_suite "$(remove_prefix "$BASE_PATH" "$1")"
  flush
}

bats_tap_stream_setup_file() {
  begin_setup_file "$(remove_prefix "$BASE_PATH" "$1")"
  flush
}

bats_tap_stream_teardown_file() {
  begin_teardown_file "$(remove_prefix "$BASE_PATH" "$1")"
  flush
}

bats_tap_stream_exit_suite() {
  # teardown_file is done -> make sure to delete its line
  retreat_additional_lines
  go_to_column 0
  clear_to_end_of_line
  flush
}

bats_tap_stream_unknown() {
  line="$1"
  scope="$2"
  # only report in interactive mode
  if [[ "${BATS_INTERACTIVE_OUTPUT-NOTSET}" != NOTSET ]]; then
    # only report within setup/teardown/tests and setup/teardown_file
    if [[ "$scope" != bats_tap_stream_plan && "$scope" != bats_tap_stream_exit_test && "$scope" != bats_tap_stream_exit_suite ]]; then
      if [[ "$line" == "bats_tap_stream_line "* ]]; then
        line="${line#bats_tap_stream_line }" # cut off prefix
        line_number="${line%% *}"
        file="${line#* }"
        test_progress "$line_number" "$file"
      else
        # forward stdout during test run or setup_file
        test_output "$line"
      fi
      flush
    fi
  fi
}

bats_parse_internal_extended_tap

[[ -n "$no_finalize_for_tests" ]] || summary
