name: Build RPM

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:
  rpm:
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/checkout@v2
      - name: Build RPM
        run: |
          dnf install -y rpm-build rpmdevtools
          rpmdev-setuptree
          rpmbuild --undefine=_disable_source_fetch -v -bb ./contrib/rpm/bats.spec
          ls -al /github/home/rpmbuild/RPMS/noarch/
          dnf install -y /github/home/rpmbuild/RPMS/noarch/bats-*.rpm
          bats --version
