name: Tests

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
 
  npm_on_linux:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: v18.20.2 
      - run: npm pack ./
      - run: npm install -g ./bats-*.tgz
      - run: echo $PATH
      - name: Run test on OS ${{ matrix.os }}
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: bats test --print-output-on-failure
