name: Tests

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add bash ncurses util-linux
      - name: Run test on bash version ${{ matrix.version }}
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run:
          time ./bin/bats  --print-output-on-failure test/

  rpm:
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/checkout@v2
      - run: dnf install -y rpm-build rpmdevtools
      - name: Build and install RPM
        run: |
          rpmdev-setuptree
          version=$(rpmspec -q --qf '%{version}' contrib/rpm/bats.spec)
          tar --transform "s,^,bats-core-${version}/," -cf /github/home/rpmbuild/SOURCES/v${version}.tar.gz ./
          rpmbuild -v -bb ./contrib/rpm/bats.spec
          ls -al /github/home/rpmbuild/RPMS/noarch/
          dnf install -y /github/home/rpmbuild/RPMS/noarch/bats-*.rpm
      - name: Run tests
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: bats --print-output-on-failure test/
