name: Tests

# Controls when the action will run.
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows:
    strategy:
      matrix:
        os: ['windows-2022', 'windows-2025']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check failing tests fail suite,
        run: bash -c "! bin/bats test/fixtures/bats/failing.bats"
      - run: |
          bash --version
          bash -c "time bin/bats -T --print-output-on-failure test"
