name: Tests

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        env_vars:
          - ''
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run test on OS ${{ matrix.os }}
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: ./bin/bats  --pretty test
